#!/bin/bash

set -x

CURL="/usr/bin/curl --silent"
JQ="/usr/local/bin/jq"

/usr/local/bin/aws s3 cp s3://fillr/sdk/details.sh .
source ./details.sh

APP_ID="7469"
TOKEN=$INSTALLRAPP_TOKEN
HEADERS="X-InstallrAppToken: $TOKEN"
ARGS="--progress-bar --verbose"
BASE_URL="https://www.installrapp.com"
ENDPOINT="apps.json"
APP_DATA_ENDPOINT="apps/$APP_ID.json"
APP_ENDPOINT="apps/$APP_ID"


APP="./app/build/outputs/apk/app-lightningPlus-debug.apk"

if (($CI == 1)); then
  APP="/tmp/app-lightningPlus-debug.apk"
fi

NOTES_FILE="./deploy/release-notes.txt"

TESTERS="$DEVS"

FILTER=".appData.latestBuild.id"

if [ ! -f $APP ]; then
  echo "No $APP to upload"
  exit
fi

if [ "$EMBEDDED" = true ] ; then
  echo " -------- " >> $NOTES_FILE
  echo "Embedded Fillr SDK Build" >> $NOTES_FILE
fi

RELEASE_NOTE=""
if [ -f $NOTES_FILE ]; then
  while read note; do
    RELEASE_NOTE="$note<br/>$RELEASE_NOTE"
  done < $NOTES_FILE
fi

$CURL -H "$HEADERS" $ARGS -XPOST "$BASE_URL/$ENDPOINT" \
  -F "qqfile=@$APP" \
  -F "releaseNotes=\"$RELEASE_NOTE\"" \
  -F "notify=\"$TESTERS\""

LATEST_BUILD_ID=$($CURL -H "$HEADERS" $ARGS -XGET "$BASE_URL/$APP_DATA_ENDPOINT" | $JQ "$FILTER")

$CURL -XPOST -H "$HEADERS" $ARGS \
  "$BASE_URL/$APP_ENDPOINT/builds/$LATEST_BUILD_ID/team.json" \
  -F "releaseNotes=\"$RELEASE_NOTE\"" \
  -F "notify=$TESTERS"
